### ISSUE TITLE
Update for Ionic 2/3

### ISSUE THREAD

**Issue by jenriquelopezdev** [AppsFlyerSDK/appsflyer-cordova-plugin#154]
# Report

## Plugin Version

6.2.40

## On what Platform are you having the issue?

Ionic 2/3

## What did you do?

I updated to version 6.2.40 but when compiling the application in android and ios it throws me an error message that the sdk is not installed.

`WARN: Ionic Native: tried calling Appsflyer.trackEvent, but the Appsflyer plugin is not installed.`
`WARN: Install the Appsflyer plugin: 'ionic cordova plugin add cordova-plugin-appsflyer-sdk'`

## What did you expect to happen?

That the SDK `@ionic-native/appsflyer@4` is updated so as not to affect my application

## What happened instead?

It throws me a message where it says that I do not have the sdk appsflyer-cordova-plugin installed

## Please provide any other relevant information.

The issue started when we upgrade the plugin to the latest version

**Comment by amit-kremer93** [comment]
Hi @jenriquelopezdev and thank you for opening this issue. the ionic-native plugin is still using our old SDK with the word `track` instead `log`. because we are not the maintainers of ionic-native, It's highly recommended to use the `window` variable and the plugin itself as shown [here](https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin#--ionic).
if you have more questions, please contact our support: suppprt@appsflyer.com
